export const CREATE_INPUTS = 'CREATE_INPUTS';
export const SELECT_INPUT = 'SELECT_INPUT';
export const SWITCH_INPUT = 'SWITCH_INPUT';
export const SELECT_OPERATIONS = 'SELECT_OPERATIONS';
export const SHOW_ANSWER = 'SHOW_ANSWER';

export const CREATE_MICRO_INPUT = 'CREATE_MICRO_INPUT';
export const CHANGE_MICRO_INPUT = 'CHANGE_MICRO_INPUT';
