export const CHANGE_VISIBILITY = 'CHANGE_VISIBILITY';
export const OPEN_KEYBOARD = 'OPEN_KEYBOARD';
export const CLOSE_KEYBOARD = 'CLOSE_KEYBOARD';
export const SET_BUTTONS = 'SET_BUTTONS';
export const PRESS_BUTTON = 'PRESS_BUTTON';
